### ISSUE TITLE
Please support unity package manager's new git feature

### ISSUE THREAD

**Issue by orangy** [BirdiePeep/UnityLight2d#1]
Manual: https://docs.unity3d.com/Manual/upm-git.html
An example of supported package: https://github.com/starikcetin/unity-scene-reference/tree/upm
Guide: https://medium.com/openupm/how-to-maintain-upm-package-part-1-7b4daf88d4c4

Thanks!

**Comment by BirdiePeep** [comment]
Added package and assembly definitions, rearranged the file structure a little to better organize files.
Package should now be accessable via the Package Manager git feature with url "https://github.com/BirdiePeep/UnityLight2d.git"

Verified the process works with a blank project.  If you experience any issues just let me know.

**Comment by orangy** [comment]
Wow! That was quick, thanks a lot :) It installs just fine, will try how it works now.

PS: in README.md you can use more markdown formatting: 
> Paste the URL "https://github.com/BirdiePeep/UnityLight2d.git" without quotes and hit "Add"

replace with

> Paste the URL `https://github.com/BirdiePeep/UnityLight2d.git` and hit "Add"

Also use headings instead of all caps, etc. If I have time today, I'll send a PR.
