### ISSUE TITLE
Rotation of parent object of a Light messes with the Spread parameter

### ISSUE THREAD

**Issue by LosTChG** [BirdiePeep/UnityLight2d#4]
In this image from the demo Scene, a rotation of 180 degrees is applied to the parent GameObject "Scene", which contains all lights. Green light has a spread value of 300º.
Is there a way to solve this "split light" phenomenon?
Thank you!

![image](https://user-images.githubusercontent.com/5962086/76266554-25e35e00-6268-11ea-8297-975cda708b2c.png)

**Comment by BirdiePeep** [comment]
Yup, looks like I was only passing in the local rotation to the shader for light spread cutoff calculation.  Pushed an updated, version 0.1.2 that should fix this issue.
